version: '3.8'

services:
  postgres:
    container_name: ireserva-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ireserva
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ireserva-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: ireserva-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: ireserva
      NODE_ENV: development
      JWT_SECRET: 'umaChaveSuperSecretaELongaParaMaiorSeguranca'
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./public/images:/app/public/images
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ireserva-network
    command: npm run dev

volumes:
  postgres_data:

networks:
  ireserva-network:
    driver: bridge 