version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ireserva-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ireserva
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: ireserva-api
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=ireserva
      - JWT_SECRET=sua_chave_secreta_muito_segura
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: npm run dev

volumes:
  postgres_data: 