CREATE TABLE IF NOT EXISTS stays (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    price_type VARCHAR(50) NOT NULL,
    img_url TEXT NOT NULL,
    rating DECIMAL(3,1) NOT NULL,
    location VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 